### ISSUE TITLE
TypeError: webpack.validateSchema is not a function

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#210]
Hi, I update poi to 9.0.0 to 9.1.0 and now, at start, I have this error :

```
TypeError: webpack.validateSchema is not a function
    at new Server (/home/throrin19/Development/vue/my-agenda/node_modules/webpack-dev-server/lib/Server.js:28:35)
    at module.exports (/home/throrin19/Development/vue/my-agenda/node_modules/poi/lib/server.js:28:18)
    at runMiddlewares.then (/home/throrin19/Development/vue/my-agenda/node_modules/poi/lib/index.js:94:16)
    at <anonymous>
```

**Comment by egoist** [comment]
remove it and install it again, sometimes there might be some cache issue.

**Comment by egoist** [comment]
Closing due to inactivity.
