### ISSUE TITLE
EJS include bug with webpack

### ISSUE THREAD

**Issue by jeffreyjw** [egoist/poi#230]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After using your own `index.ejs`, and using `<%- include('somestuff.ejs'); %>` the compilation process with `poi` command is throwing a webpack error - first thought it might be a directory problem, but tried different patterns: `./kv.ejs`, `kv`, `kv.ejs`, `../kv.ejs`, `require('./kv.ejs')` and nothing helps. The message is also cryptic, so debugging is problematic.
**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a file called index.ejs:

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title><%= htmlWebpackPlugin.options.title %></title>
    <% if (htmlWebpackPlugin.options.description) { %>
    <meta name="description" content="<%= htmlWebpackPlugin.options.description %>"/>
    <% } %>
  </head>
  <body>
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <%- include('kv.ejs', {}); %>
    <div id="app"></div>
    <div>Ola!</div>
  </body>
</html>
```

2. create a file called `kv.ejs`:
```
<div class="kv">
    KV
</div>
```
3. Run `poi` or `poi build` - an error message is generated

```
/home/jeffrey/Projects/my-project/node_modules/poi/lib/webpack/handle-errors/index.js:46
  if (error.stack.indexOf('eslint-loader') >= 0) {
                 ^

TypeError: Cannot read property 'indexOf' of undefined
    at formatError (/home/jeffrey/Projects/my-project/node_modules/poi/lib/webpack/handle-errors/index.js:46:18)
    at Array.map (native)
    at module.exports.errors (/home/jeffrey/Projects/my-project/node_modules/poi/lib/webpack/handle-errors/index.js:85:19)
    at Compiler.compiler.plugin.stats (/home/jeffrey/Projects/my-project/node_modules/poi/lib/webpack/fancy-log-plugin.js:28:9)
    at Compiler.applyPlugins (/home/jeffrey/Projects/my-project/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/home/jeffrey/Projects/my-project/node_modules/webpack/lib/Compiler.js:104:17)
    at compiler.emitRecords.err (/home/jeffrey/Projects/my-project/node_modules/webpack/lib/Compiler.js:78:19)
    at Compiler.emitRecords (/home/jeffrey/Projects/my-project/node_modules/webpack/lib/Compiler.js:375:38)
    at compiler.emitAssets.err (/home/jeffrey/Projects/my-project/node_modules/webpack/lib/Compiler.js:61:20)
    at applyPluginsAsyncSeries1.err (/home/jeffrey/Projects/my-project/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/home/jeffrey/Projects/my-project/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/jeffrey/Projects/my-project/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at next (/home/jeffrey/Projects/my-project/node_modules/tapable/lib/Tapable.js:220:14)
    at callback (/home/jeffrey/Projects/my-project/node_modules/copy-webpack-plugin/dist/index.js:108:17)
    at Compiler.<anonymous> (/home/jeffrey/Projects/my-project/node_modules/copy-webpack-plugin/dist/index.js:131:13)
    at Compiler.applyPluginsAsyncSeries1 (/home/jeffrey/Projects/my-project/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/jeffrey/Projects/my-project/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/home/jeffrey/Projects/my-project/node_modules/webpack/lib/Compiler.js:354:15)
    at /home/jeffrey/Projects/my-project/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/jeffrey/Projects/my-project/node_modules/async/dist/async.js:998:13)
    at /home/jeffrey/Projects/my-project/node_modules/async/dist/async.js:906:16
    at MemoryFileSystem.writeFile (/home/jeffrey/Projects/my-project/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
error Command failed with exit code 1
```

No POI configuration set, just these two files are needed to reproduce

**What is the expected behavior?**
A compiled project ;)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

Operating system: Linux Mint 18 Sarah
Node.js version: 6.7.0
Poi version: 9.3.3

**Comment by jeffreyjw** [comment]
Closing the issue - after more research I found that you are using underscore ejs templates from `webpack-html-plugin` that do not have this feature, but for anyone that would like to have this, you only need to add (for ejs-compiled-loader):

`yarn add ejs-compiled-loader`

and in the poi.config.js:

```
module.exports = {
  html: {
    title: 'title',
    description: 'desc',
    template: '!!ejs-compiled-loader!index.ejs',
  }
}
```

And this will work

**Comment by gilesbutler** [comment]
Awewsome!! Thanks for sharing @jeffreyjw
