### ISSUE TITLE
Error when building a simple vue index.js

### ISSUE THREAD

**Issue by aVolpe** [egoist/poi#234]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

When running `poi build` a `TypeError: extractedChunk.getNumberOfModules is not a function` appear.

Execute:

```
vi index.js # and put the example Vue code

poi # a new dev server start and everything works fine

poi build # to test the build
```

Stack:

```

TypeError: extractedChunk.getNumberOfModules is not a function
    at ExtractTextPlugin.<anonymous> (/$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/dist/index.js:246:32)
    at Array.forEach (native)
    at Compilation.<anonymous> (/$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/dist/index.js:245:27)
    at Compilation.applyPluginsAsyncSeries (/$HOME/.config/yarn/global/node_modules/poi/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/$HOME/.config/yarn/global/node_modules/poi/node_modules/webpack/lib/Compilation.js:653:9)
    at next (/$HOME/.config/yarn/global/node_modules/poi/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/$HOME/.config/yarn/global/node_modules/poi/node_modules/webpack/lib/ProgressPlugin.js:111:6)
    at next (/$HOME/.config/yarn/global/node_modules/poi/node_modules/tapable/lib/Tapable.js:204:14)
    at /$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/dist/index.js:241:13
    at /$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
    at /$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:906:16
    at /$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/dist/index.js:224:15
    at /$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at eachOfArrayLike (/$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:991:9)
    at eachOf (/$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3145:5)
    at /$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/dist/index.js:189:29
    at /$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1003:9)
    at eachOf (/$HOME/.config/yarn/global/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1051:5)
 
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The command succeed and a `dist` folder is created

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

yarn 0.31.3
node v7.7.2
poi 9.3.5 (it's a fresh install)

**Comment by egoist** [comment]
Hmm weird, it works fine for me on a fresh docker node instance, maybe some yarn issue? try re-install it or install it locally in your project.

**Comment by aVolpe** [comment]
@egoist with only a file in the folder with this content:

```js
import Vue from 'vue'

new Vue({
  el: '#app',
  render() {
    return <h1>Hello Vue.</h1>
  }
})
```

And running `poi build` it fails with the original message, but
if I do:

1. yarn init 
2. yarn add --dev poi
3. ./node_modules/.bin/poi build

It's works fine, thanks for the support!.

**Comment by egoist** [comment]
@aVolpe btw you can run the local bin with `yarn poi` or `npx poi` if you have npm^5.3
