### ISSUE TITLE
Error when adding plugins

### ISSUE THREAD

**Issue by DrSensor** [egoist/poi#325]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
It produces error below when trying to add webpack plugin
```
TypeError: config.plugins.push is not a function
    at extendWebpack (/home/wildan/Projects/OSS/vue-annotator/.storybook/poi.config.js:30:20)
    at webpackFlows.forEach.flow (/home/wildan/Projects/OSS/vue-annotator/node_modules/poi/lib/index.js:77:39)
    at Array.forEach (<anonymous>)
    at Poi.createWebpackConfig (/home/wildan/Projects/OSS/vue-annotator/node_modules/poi/lib/index.js:77:23)
    at Promise (/home/wildan/Projects/OSS/vue-annotator/node_modules/poi/lib/index.js:187:34)
    at new Promise (<anonymous>)
    at Poi.runMiddlewares (/home/wildan/Projects/OSS/vue-annotator/node_modules/poi/lib/index.js:186:12)
    at prepare.then (/home/wildan/Projects/OSS/vue-annotator/node_modules/poi/lib/index.js:115:24)
    at <anonymous>
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Using this config, (sorry for leaving the inline comment)
```js
const FlowtypePlugin = require('flowtype-loader/plugin')

module.exports = {
  /** BUG(in vue-loader maybe): Can't use lazy load import when specify custom loader
  @config
  vue: {
    loaders: {
      docs: require.resolve('../.loader/docs-loader.js'),
      notes: require.resolve('../.loader/notes-loader.js'),
      info: require.resolve('../.loader/info-loader.js')
    }
  },
  */

  // Entry is relative to process.cwd()
  entry: [
    '.storybook/config.js',
    '.storybook/addons.js'
  ],

  extendWebpack (config) {

    config.module.rule('markdown')
      .test(/\.md$/)
      .use('md')
      .loader(require.resolve('raw-loader'))
    
    /** @throws ERROR HERE */
    config.plugins.push(new FlowtypePlugin())
    config.module.rule('js')
      .test(/\.(js|jsx)$/)
      .loader(require.resolve('flowtype-loader'))

  },

  dist: '.storybook/dist',

  presets: [
    require('poi-preset-storybook')()
  ]
}
```
then run `poi build --config .storybook/poi.config.js --storybook`

**What is the expected behavior?**
no error

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Poi 1.1.2
Node.js 8.9.3

**Comment by egoist** [comment]
`config` is a webpack-chain instance, there's no `config.plugins.push`
