### ISSUE TITLE
Vue packages version mismatch error when importing external vue component

### ISSUE THREAD

**Issue by lesaff** [egoist/poi#401]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Build throwing the following error 
```
Failed to compile.

./src/components/App.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.1.10
- vue-template-compiler@2.5.13

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/rudy/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rudy/node_modules/vue-loader/lib/parser.js:1:80)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rudy/node_modules/vue-loader/lib/loader.js:3:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
 @ ./index.js 3:0-43
 @ multi /Users/rudy/.config/yarn/global/node_modules/poi/app/dev-client.es6 ./index.js
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I am trying to import an external `.vue` file into my app. I tried installing `vue` and `vue-template-compiler` on my project to no avail.

**What is the expected behavior?**
External template compiled successfully.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Chrome v65.x
Node v8.9.3
Poi v9.6.13
Mac OS 10.13.3 (High Sierra)

**Comment by egoist** [comment]
Try `yarn add vue poi --dev`

**Comment by lesaff** [comment]
That works! Thanks for a super-quick response 💯 
I will run `poi` locally from now on.
