### ISSUE TITLE
poi 10 trying to load poi.config.ts as a json file

### ISSUE THREAD

**Issue by cj** [egoist/poi#419]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
poi is trying to parse `poi.config.ts` as json.

```
17:49 ◯ : npx poi --require ts-node/register --config poi.config.ts
JSONError: Unexpected token 'i' at 1:1 in poi.config.ts
import { Options } from 'poi'
^
import { Options } from 'poi'
^
    at module.exports (/Users/cj/apps/vodr/poi/node_modules/parse-json/index.js:27:17)
        at parse (/Users/cj/apps/vodr/poi/node_modules/load-json-file/index.js:8:29)
            at pify.then.data (/Users/cj/apps/vodr/poi/node_modules/load-json-file/index.js:10:67)
                at <anonymous>

```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/cj/3465de10e69d7eaf2b171a9b73d27480

`npx poi --require ts-node/register --config poi.config.ts`

**What is the expected behavior?**

It should run poi :)

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

poi: 10.0.3

**Comment by cj** [comment]
Looks like the issue is with https://github.com/egoist/use-config/blob/master/src/index.js#L30.  @egoist do you want me to open up a ticket there?

**Comment by egoist** [comment]
I will fix it in Poi (and update the d.ts file)

**Comment by egoist** [comment]
10.1.0 should work.

**Comment by cj** [comment]
@egoist works, thank you!

One other thing I just noticed.  It now says `TypeScript is supported by default, no need to require ts-node/register`, if that's the case, it might be nice to look for `poi.config.ts` by default to get rid of the need for `--config poi.config.ts`, thoughts?

**Comment by egoist** [comment]
Good idea, try 10.1.1

**Comment by cj** [comment]
@egoist you are truly a legend!

**Comment by cj** [comment]
@egoist looks like there's one caveat, I don't think it's picking up the tsconfig.json.  I created https://glitch.com/edit/#!/poi-typescript to play around with.

**Comment by cj** [comment]
ah, I think it's actually the `ts-loader`

**Comment by cj** [comment]
```
Module build failed: TypeError: Cannot read property 'ts' of undefined
    at getLoaderOptions (/Users/cj/apps/vodr/poi/node_modules/ts-loader/dist/index.js:70:44)
        at Object.loader (/Users/cj/apps/vodr/poi/node_modules/ts-loader/dist/index.js:23:19)
```

looks like the error above is to do with https://github.com/TypeStrong/ts-loader/issues/726#issuecomment-376119771. Upgrading to `"ts-loader": "^4.2.0"` fixes that error, but leads to another.

```
Module build failed: Error: Could not find file: '/Users/cj/apps/vodr/poi/client/App.vue'.
at getValidSourceFile (/Users/cj/apps/vodr/poi/node_modules/typescript/lib/typescript.js:103059:23)
at Object.getEmitOutput (/Users/cj/apps/vodr/poi/node_modules/typescript/lib/typescript.js:103402:30)
at Object.getEmitOutput (/Users/cj/apps/vodr/poi/node_modules/ts-loader/dist/instances.js:184:41)
at getEmit (/Users/cj/apps/vodr/poi/node_modules/ts-loader/dist/index.js:188:37)
at successLoader (/Users/cj/apps/vodr/poi/node_modules/ts-loader/dist/index.js:34:11)
at Object.loader (/Users/cj/apps/vodr/poi/node_modules/ts-loader/dist/index.js:21:12)

Cannot import file "./router" from "/Users/cj/apps/vodr/poi/client"! Are you sure it exists?
```

**Comment by egoist** [comment]
for `paths` in `tsconfig.json` seems we still need to add tsconfig-paths-webpack-plugin

**Comment by cj** [comment]
looks like it's still an issue https://glitch.com/edit/#!/poi-typescript

**Comment by egoist** [comment]
Not sure what's going on there, it works fine locally.

**Comment by cj** [comment]
I have the same issue locally as on glitch, I tried a clean install too.

**Comment by egoist** [comment]
👌 now, I've updated https://github.com/poi-examples/vue-ts-example too

**Comment by cj** [comment]
@egoist works like a charm now -- thank you again!
