### ISSUE TITLE
Webpack Options Validation Error

### ISSUE THREAD

**Issue by SimplyCodin** [egoist/poi#420]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
🚨  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a
 configuration object that does not match the API schema.
 - configuration.module.rules[20].use should be one of these:
   non-empty string | function | object { loader?, options?, ident?, query? } | function | [non-empty string | function | object { loader?, options?, ident?, query? }]
   -> Modifiers applied to the module when rule is matched
   Details:
    * configuration.module.rules[20].use should be a string.
    * configuration.module.rules[20].use should be an instance of function
    * configuration.module.rules[20].use should be an object.
    * configuration.module.rules[20].use should be an instance of function
    * configuration.module.rules[20].use[0] should be a string.
    * configuration.module.rules[20].use[0] should be an instance of function
    * configuration.module.rules[20].use[0].loader should be a string.
    at webpack (PROJECT\node_modules\webpack\lib\webpack.js:24:9)
    at Poi.createCompiler (PROJECT\fallproject.github.io\node_modules\poi\lib\index.js:104:50)
    at Poi.runCompiler (PROJECT\fallproject.github.io\node_modules\poi\lib\index.js:113:27)
    at Command.poi.cli.handleCommand [as handler] (PROJECT\fallproject.github.io\node_modules\poi\lib\plugins\build.js:7:15)
    at Cac.parse (PROJECT\Desktop\fallproject.github.io\node_modules\cac\dist\cac.js:418:27)
    at CLI.runCommand (PROJECT\node_modules\poi\lib\cliEngine.js:32:21)
    at Poi.run (PROJECT\node_modules\poi\lib\index.js:224:32)
    at <anonymous>

**If the current behavior is a bug, please provide the steps to reproduce.**
[Poi Config File](https://gist.github.com/SimplyCodin/2120c5977ffb408dabc7eafaec8ed1e4)

**What is the expected behavior?**
For there not to be a validation error with a built in Webpack Chain fucntion.

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Poi: 10.1.2
Node: v9.2.1

**Comment by egoist** [comment]
Forgot to add `copy` to the docs, now added https://poi.js.org/options.html#copy

btw `copy-webpack-plugin` is a webpack plugin so you should use `config.plugin` instead.

**Comment by egoist** [comment]
@SimplyCodin wondering what is your use case of using `copy`, we already copy `static/**` to the root of output directory. 🤔

**Comment by SimplyCodin** [comment]
I use it to simply my assets workflow.
