### ISSUE TITLE
Svelte V2

### ISSUE THREAD

**Issue by ansarizafar** [egoist/poi#422]
Svelte V2 has been released yesterday. Please update Svelte plugin. I am currently getting this error with poi V10.1.1 

```
zafar@home:~/projects/tailwindcss$ poi
🚨  TypeError: Cannot read property 'rule' of undefined
    at poi.chainWebpack.config (/home/zafar/projects/tailwindcss/node_modules/@poi/plugin-svelte/index.js:19:12)
    at hooks.get.forEach.fn (/home/zafar/.nvm/versions/node/v9.1.0/lib/node_modules/poi/lib/utils/hooks.js:18:9)
    at Set.forEach (<anonymous>)
    at Hooks.invoke (/home/zafar/.nvm/versions/node/v9.1.0/lib/node_modules/poi/lib/utils/hooks.js:17:28)
    at Poi.createWebpackConfig (/home/zafar/.nvm/versions/node/v9.1.0/lib/node_modules/poi/lib/index.js:261:16)
    at Poi.createCompiler (/home/zafar/.nvm/versions/node/v9.1.0/lib/node_modules/poi/lib/index.js:103:43)
    at Command.poi.cli.handleCommand [as handler] (/home/zafar/.nvm/versions/node/v9.1.0/lib/node_modules/poi/lib/plugins/develop.js:24:28)
    at Cac.parse (/home/zafar/.nvm/versions/node/v9.1.0/lib/node_modules/poi/node_modules/cac/dist/cac.js:418:27)
    at CLI.runCommand (/home/zafar/.nvm/versions/node/v9.1.0/lib/node_modules/poi/lib/cliEngine.js:32:21)
    at Poi.run (/home/zafar/.nvm/versions/node/v9.1.0/lib/node_modules/poi/lib/index.j
```
Here is my poi configuration. My app was working correctly with poi Ver 9.*
````
module.exports = {
    //entry: './src/index.js', 
    plugins: [
        require('@poi/plugin-svelte')({loaderOptions: {emitCss: true, parser: 'v2'}})
      ]
    }
````

**Comment by egoist** [comment]
This error is not related to svelte 2, so I just updated the `plugin-svelte` to fix this.

Will try to update to Svelte 2 later.

**Comment by ansarizafar** [comment]
I have updated the plugin but now I am getting this error
````
Failed to compile with 2 errors

Cannot find module "babel-loader" in "/home/zafar/projects/tailwindcss"!
You may run npm install babel-loader to install missing dependencies.
You may also append -D flag for devDependencies.

Cannot find module "vue-style-loader" in "/home/zafar/projects/tailwindcss"!
You may run npm install vue-style-loader to install missing dependencies.
You may also append -D flag for devDependencies.
````

**Comment by egoist** [comment]
try reinstall your node_modules, not sure what is going on there.

**Comment by ansarizafar** [comment]
I have reinstalled node_modules but still getting same error.

**Comment by egoist** [comment]
Install Poi locally 😄

**Comment by ansarizafar** [comment]
Now I have installed poi locally. Poi is showing progress bar but no errors then stop
![image](https://user-images.githubusercontent.com/5788284/39055727-5d4d43c4-44ce-11e8-9399-b2ab3dcffe65.png)

**Comment by ansarizafar** [comment]
Its working now. Thanks for your help. There were few errors in Svelte code but poi was not reporting them. I am using poi locally as globally installed poi is not working. Is there any solution available to use globally installed poi?

**Comment by egoist** [comment]
providing steps to reproduce this error on a fresh docker instance would help.

btw it's generally better to install poi locally for production apps.

> There were few errors in Svelte code but poi was not reporting them.

If you think it is a bug in Poi, then PR welcome 😄
