### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by ChiaJune** [egoist/poi#436]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
get an error

``` bash
Error: Cannot find module 'C:\Users\xxx\Desktop\test3\node_modules\poi-plugin-[object Object]'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at getFn (C:\Users\xxx\Desktop\test3\node_modules\parse-json-config\index.js:25:10)
    at config.map.item (C:\Users\xxx\Desktop\test3\node_modules\parse-json-config\index.js:48:18)
    at Array.map (<anonymous>)
    at module.exports (C:\Users\xxx\Desktop\test3\node_modules\parse-json-config\index.js:38:19)
    at Poi.registerPlugins (C:\Users\xxx\Desktop\test3\node_modules\poi\lib\index.js:146:26)
    at Poi.prepare (C:\Users\xxx\Desktop\test3\node_modules\poi\lib\index.js:212:12)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

When I use the `poi` command to start the service, I get an error

**What is the expected behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**OS**：macOS10.13.4 & window10
**browser version**：66.0.3359.181
**Node.js version**：8.10.0
**Poi version**：10.1.8

**package.json**

``` json
{
  "name": "test3",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "build": "./node_modules/.bin/poi build",
    "dev": "./node_modules/.bin/poi"
  },
  "devDependencies": {
    "@poi/plugin-typescript": "^10.1.4",
    "@types/node": "^10.1.1",
    "@types/react": "^16.3.14",
    "@types/react-dom": "^16.0.5",
    "@types/react-hot-loader": "^4.1.0",
    "node-sass": "^4.9.0",
    "poi": "^10.1.8",
    "react-hot-loader": "^4.2.0",
    "sass-loader": "^7.0.1",
    "tslint": "^5.10.0",
    "tslint-react": "^3.6.0",
    "typescript": "^2.8.3"
  },
  "dependencies": {
    "react": "^16.3.2",
    "react-dom": "^16.3.2"
  }
}
```

**poi.config.js**
``` javascript
module.exports = {
  entry: 'src/index.tsx',
  port: 8087,
  plugins: [
    require('@poi/plugin-typescript')()
  ]
}
```

**Comment by gustav-vidispine** [comment]
We're having the exact same issue since yesterday with `plugin-eslint`

**poi.config.js**
```
plugins: [
    require('@poi/plugin-eslint')({
      loaderOptions: {
        exclude: /node_modules/,
        configFile: '.eslintrc.js',
        fix: true
      },
      command: ['develop', 'build']
    })
```

**Comment by gustav-vidispine** [comment]
@ChiaJune try downgrading @poi/plugin-typescript to an older version, worked for me with plugin-eslint :)

**Comment by pierrebiver** [comment]
Have the exact same issue with plugin-typescript@10.1.4

**Comment by egoist** [comment]
Try reinstalling Poi to fix this.

**Comment by pierrebiver** [comment]
I updated with the version 10.1.9 and it works now.
