### ISSUE TITLE
Error: Cannot find module 'uglifyjs-webpack-plugin'

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#491]
Hello, When I try to compile my code this morning, I have this error : 

```
poi build
 🚨 Error: Cannot find module 'uglifyjs-webpack-plugin'
 at Function.Module._resolveFilename (module.js:547:15)
 at Function.Module._load (module.js:474:25)
 at Module.require (module.js:596:17)
 at require (internal/module.js:11:18)
 at Object.apply (/codebuild/output/src731612786/src/node_modules/@poi/core/createWebpackConfig.js:222:38)
 at WebpackOptionsApply.process (/codebuild/output/src731612786/src/node_modules/webpack/lib/WebpackOptionsApply.js:468:16)
 at webpack (/codebuild/output/src731612786/src/node_modules/webpack/lib/webpack.js:53:48)
 at Poi.createCompiler (/codebuild/output/src731612786/src/node_modules/poi/lib/index.js:104:50)
 at Poi.runCompiler (/codebuild/output/src731612786/src/node_modules/poi/lib/index.js:113:27)
 at Command.poi.cli.handleCommand [as handler] (/codebuild/output/src731612786/src/node_modules/poi/lib/plugins/build.js:9:17)
 at Cac.parse (/codebuild/output/src731612786/src/node_modules/cac/dist/cac.js:418:27)
 at CLI.runCommand (/codebuild/output/src731612786/src/node_modules/poi/lib/cliEngine.js:32:21)
 at Poi.run (/codebuild/output/src731612786/src/node_modules/poi/lib/index.js:240:32)
 at <anonymous>
```

The build works correctly the last time I test this 4 days ago in my CI server.

Have you change dependencies requirements in v10.x ?? It's possible to fix that really quickly ? My production build is break by this error :/

This is my devDependencies : 

"@babel/core": "7.0.0-rc.2",
"@babel/plugin-proposal-class-properties": "7.0.0-rc.2",
"@babel/plugin-proposal-decorators": "7.0.0-rc.2",
"@babel/plugin-proposal-object-rest-spread": "7.0.0-rc.2",
"@babel/plugin-syntax-dynamic-import": "7.0.0-rc.2",
"@babel/plugin-transform-runtime": "7.0.0-rc.2",
"@babel/preset-env": "7.0.0-rc.2",
"@babel/runtime": "7.0.0-rc.2",
"@poi/plugin-bundle-report": "10.0.1",
"@poi/plugin-eslint": "10.0.2",
"@poi/plugin-karma": "10.0.3",
"@poi/plugin-offline": "10.0.1",
"@vue/test-utils": "1.0.0-beta.24",
"babel-eslint": "8.2.6",
"babel-plugin-lodash": "3.3.4",
"babel-preset-vue": "2.0.2",
"chai": "4.1.2",
"eslint": "5.4.0",
"eslint-config-throrinstudio": "1.3.0",
"eslint-loader": "2.1.0",
"eslint-plugin-import": "2.14.0",
"eslint-plugin-vue": "4.7.1",
"karma-chai": "0.1.0",
"offline-plugin": "5.0.5",
"poi": "10.2.10",
"prettier-eslint": "8.8.2",
"serve": "10.0.0",
"sinon": "6.1.5",
"stylus": "0.54.5",
"stylus-loader": "3.0.2",
"vue-eslint-parser": "3.2.2",
"webpack-pwa-manifest": "3.7.1",
"xlsx": "0.13.4"

**Comment by egoist** [comment]
Webpack replaced uglifyjs with terser yesterday 😅

**Comment by throrin19** [comment]
Why ?! this is really bullshit. Normally all breaking changes were made with new versions, not with currently used

**Comment by egoist** [comment]
Fixed in 10.2.11

**Comment by throrin19** [comment]
Thanks for your fix and your reactivity !! You're awesome !!

**Comment by lili21** [comment]
Unexpected token: keyword (const).

**Comment by dashdotdawn** [comment]
Hello, it seems that there is no release version for v11 with this fixed, I have to yarn add poi from repository now.

**Comment by cadejscroggins** [comment]
@egoist, thank you for all you do.

As @lili21 mentioned, I'm seeing this:

```
[1:37:18 PM] Compiling Poi
[1:37:27 PM] Compiled Poi in 8s
🚨 Failed to compile with 1 errors

4.f572cfa9.js from UglifyJs
Unexpected token: keyword (const) [./node_modules/query-string/index.js:2,0][4.f572cfa9.js:75,0]
```

Poi `v10.2.11`. Any ideas or do you need more info?

**Comment by cadejscroggins** [comment]
Nevermind, added:

```javascript
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  configureWebpack(config) {
    config.output.globalObject = 'this';
    config.optimization = { minimizer: [new TerserPlugin()] }
    return config;
  },
  entry: 'src/index.js',
  html: { template: 'src/index.html' },
  babel: { jsx: 'react' },
};
```

Works now.
