### ISSUE TITLE
Error: Cannot find module 'html-webpack-plugin'

### ISSUE THREAD

**Issue by maple3142** [egoist/poi#500]
It doesn't work even if I install `html-webpack-plugin` manually.

<details>
<summary>log</summary>

```cmd
C:\Users\Administrator\Documents\GitHub\WynnStats (master) >yarn build
yarn run v1.9.4
warning ..\package.json: No license field
$ poi --prod
Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at new PwaHtmlWebpackPlugin (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\pwa-html-webpack-plugin\index.js:24:51)
    at init (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\webpack-chain\src\Plugin.js:14:18)
    at Object.toConfig (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\webpack-chain\src\Plugin.js:60:22)
    at clean.Object.assign.plugins.plugins.values.map.plugin (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\webpack-chain\src\Config.js:129:61)
    at Array.map (<anonymous>)
    at WebpackChain.toConfig (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\webpack-chain\src\Config.js:129:40)
    at WebpackChain.toConfig (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\lib\utils\WebpackChain.js:12:24)
    at CAC.command.action (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\lib\index.js:125:57)
    at CAC.runMatchedCommand (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\cac\dist\index.js:756:38)
    at PoiCore.run (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\lib\index.js:270:20)
    at main (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\bin\cli.js:14:15)
    at Object.<anonymous> (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\bin\cli.js:28:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Administrator\Documents\GitHub\WynnStats (master) >yarn add -D html-webpack-plugin
yarn add v1.9.4
warning ..\package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/1050(node:8124) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@4.1.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.1.0" has unmet peer dependency "popper.js@^1.14.0".
warning "bootstrap-vue > bootstrap@4.1.3" has unmet peer dependency "jquery@1.9.1 - 3".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ html-webpack-plugin@3.2.0
info All dependencies
├─ html-webpack-plugin@3.2.0
└─ toposort@1.0.7
Done in 6.97s.

C:\Users\Administrator\Documents\GitHub\WynnStats (master) >yarn build
yarn run v1.9.4
warning ..\package.json: No license field
$ poi --prod
- 0.00% compiling TypeError: HtmlWebpackPlugin.getHooks is not a function
    at compiler.hooks.compilation.tap.compilation (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\pwa-html-webpack-plugin\index.js:84:25)
    at SyncHook.eval [as call] (eval at create (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:19:1)
    at SyncHook.lazyCompileHook (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\node_modules\webpack\lib\Compiler.js:503:26)
    at hooks.beforeCompile.callAsync.err (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\node_modules\webpack\lib\Compiler.js:539:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\node_modules\webpack\lib\Compiler.js:534:28)
    at readRecords.err (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\node_modules\webpack\lib\Compiler.js:274:11)
    at Compiler.readRecords (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\node_modules\webpack\lib\Compiler.js:401:11)
    at hooks.run.callAsync.err (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\node_modules\webpack\lib\Compiler.js:271:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\poi\node_modules\webpack\lib\Compiler.js:268:19)
    at _promise1.then._result1 (eval at create (C:\Users\Administrator\Documents\GitHub\WynnStats\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:22:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

<details>
<summary>package.json</summary>

```js
{
	"name": "wynnstats",
	"version": "1.0.0",
	"license": "MIT",
	"main": "index.js",
	"scripts": {
		"build": "poi --prod",
		"dev": "poi --serve"
	},
	"dependencies": {
		"bootstrap": "4.1.0",
		"bootstrap-vue": "^2.0.0-rc.2",
		"change-case": "^3.0.1",
		"dexie": "^2.0.2",
		"escape-string-regexp": "^1.0.5",
		"font-awesome": "^4.7.0",
		"lodash": "^4.17.4",
		"register-service-worker": "^1.5.2",
		"vue": "^2.5.17",
		"vue-infinite-loading": "^2.2.1",
		"vue-router": "^3.0.1",
		"vue-spinner": "^1.0.3",
		"vuejs-storage": "^3.0.1",
		"webpack": "^4.20.2",
		"whatwg-fetch": "^2.0.3",
		"xfetch-js": "^0.3.0"
	},
	"devDependencies": {
		"@babel/core": "^7.1.2",
		"@poi/plugin-pwa": "^12.0.0",
		"babel-eslint": "^10.0.1",
		"eslint": "^5.10.0",
		"eslint-plugin-vue": "^5.0.0",
		"html-webpack-plugin": "^3.2.0",
		"poi": "^12.0.0"
	}
}
```
</details>

<details>
<summary>poi.config.js</summary>

```js
module.exports = {
	entry: './src/index.js',
	output: {
		html: {
			title: 'WynnStats',
			description: 'A browser client can view WynnCraft stats.'
		}
	},
	plugins: [
		{
			resolve: '@poi/plugin-pwa',
			options: {}
		}
	]
}
```
</details>

**Comment by egoist** [comment]
Should work in @poi/plugin-pwa 12.0.1 it requires html-webpack-plugin^4
