### ISSUE TITLE
VuetifyLoader plugin problem

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#632]
Hello,

I try to use VuetifyLoader plugin with poi but I have a problem when I add it in poi.config.js.

On compilation, I have this error : 

```
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (/manager-app/node_modules/vuetify-loader/lib/plugin.js:18:13)
    at webpack (/manager-app/node_modules/webpack/lib/webpack.js:51:13)
    at PoiCore.createWebpackCompiler (/manager-app/node_modules/poi/lib/index.js:466:40)
    at CAC.command.action (/manager-app/node_modules/poi/lib/plugins/serve.js:51:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

It seems POI has no rule for vue-loader. But, If I try to load vue project, I have no problem.
How to fix that ?

Thanks

**Comment by egoist** [comment]
We do have a rule that uses vue-loader: https://github.com/egoist/poi/blob/master/core/poi/lib/plugins/config-vue.js

**Comment by egoist** [comment]
Vuetify Loader checks if the loader name is `vue-loader`:

https://github.com/vuetifyjs/vuetify-loader/blob/01ec5f1799844bd1500fc9e1f789e60954508b12/lib/plugin.js#L14

But we use absolute path 😅 It should be fixed on their side.

**Comment by throrin19** [comment]
I go to vuetifyLoaderPlugin project to show what we have this error :/
It's weird
