### ISSUE TITLE
plugin-pwa bug

### ISSUE THREAD

**Issue by tabaktoni** [egoist/poi#759]
`   const HtmlWebpackPlugin = config.plugins.has('html-page-0')
      ? config.plugin('html-page-0').get('plugin')
      : config.plugin('html').get('plugin');`

Plugin pwa here return undefined and so build fail with:
TypeError: Cannot read property '__expression' of undefined
    at Object.toConfig (/Users/toni/Work/scst-booking/node_modules/webpack-chain/src/Plugin.js:56:38)
    at /Users/toni/Work/scst-booking/node_modules/webpack-chain/src/Config.js:131:61
    at Array.map (<anonymous>)
    at WebpackChain.toConfig (/Users/toni/Work/scst-booking/node_modules/webpack-chain/src/Config.js:131:40)
    at WebpackChain.toConfig (/Users/toni/Work/scst-booking/node_modules/poi/lib/utils/WebpackChain.js:12:24)
    at CAC.<anonymous> (/Users/toni/Work/scst-booking/node_modules/poi/lib/index.js:147:59)
    at CAC.runMatchedCommand (/Users/toni/Work/scst-booking/node_modules/cac/dist/index.js:597:34)
    at PoiCore.run (/Users/toni/Work/scst-booking/node_modules/poi/lib/index.js:336:20)
    at async main (/Users/toni/Work/scst-booking/node_modules/poi/bin/cli.js:14:5)

**Comment by tabaktoni** [comment]
i use Poi pages
